# Generated by Django 4.1.3 on 2022-12-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_allservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phonenum', models.CharField(max_length=15)),
                ('cityname', models.CharField(max_length=100)),
                ('serviced', models.CharField(max_length=100)),
                ('datebook', models.DateField()),
            ],
        ),
    ]
