# Generated by Django 4.1.3 on 2022-12-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='statusbook',
            field=models.BooleanField(default=False),
        ),
    ]
