# Generated by Django 4.1.3 on 2022-12-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_booking_statusbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='normalstatus',
            field=models.BooleanField(default=True),
        ),
    ]
