# Generated by Django 4.1.3 on 2023-01-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_booking_normalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='justurke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
